services:
  main:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/DockerfileDev
    ports:
      - ${OUTER_SERVER_PORT}:${SERVER_PORT}
      - ${OUTER_UI_PORT}:5173
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
