services:
  main:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/DockerfileProd
    ports:
      - ${SERVER_PORT}:3000
      - ${UI_PORT}:80
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/src:/app/server/src
      - ./ui/src:/app/ui/src
