services:
  main:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/DockerfileProd
    ports:
      - ${OUTER_SERVER_PORT}:${SERVER_PORT}
      - ${OUTER_UI_PORT}:80
    environment:
      - NODE_ENV=production
